chore: rearrange storybook
sahabpardaz/gooni pull request #7
Opened 2022-05-22 12:29 UTC by mdeljavan

2022-05-22 13:24 UTC, m-davoodi commented on .yarnrc
> +registry "https://registry.yarnpkg.com/"
add new line

2022-05-22 13:27 UTC, mh-alahdadian requested changes

2022-05-22 13:27 UTC, mh-alahdadian commented on .yarnrc
> +registry "https://registry.yarnpkg.com/"
add new line at end

2022-05-22 13:27 UTC, mh-alahdadian commented on packages/mui/package.json
> +    "stylis-plugin-rtl": "^2.1.1",
why too many changes ?

2022-05-22 13:27 UTC, mh-alahdadian commented on tsconfig.base.json
> +    "noUnusedParameters": false,
why?!

2022-05-22 13:27 UTC, mh-alahdadian commented on packages/mui/src/stories/stories/OverlayScrollbar.stories.tsx
> +import { ImperativeHandles, PxOverlayScrollbar } from '../..';
could be move to `@sahab/react` instead

2022-05-23 07:39 UTC, m-davoodi approved these changes

2022-05-23 07:41 UTC, merged